spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lantern/
    username: root
    password: jay1363600
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9025

dubbo:
  scan:
    base-packages: com.lamp.lantern.bussiness.operator.provider.service.impl
  application:
    name: lamp-lantern-bussiness-operator
    owner: dome
    logger: slf4j
  protocol:
    name: dubbo
    port: 20880
    accesslog: true
  provider:
    timeout: 30000
    retries: 0
  registry:
    address: nacos://124.223.198.143:8848
    parmeters:
      namespace: lantern-dev
    register: true
    subscribe: true


