server:
  port: 9022
  servlet:
    context-path: "/"

dubbo:
  protocol:
    name: dubbo
    port: 20880
    accesslog: true
  consume:
    timeout: 30000
    retries: 0
  registry:
    address: nacos://124.223.198.143:8848
    parmeters:
      namespace: lantern-dev
    register: true
    subscribe: true
  scan:
    base-packages: com.lamp.lantern.bussiness.operator.consumers.controller
  application:
    name: lamp-lantern-bussiness-operator
    owner: dome
    logger: slf4j
